*Importando o Pandas*

In [1]:
import pandas as pd

#definindo quantidade de linhas e colunas visiveis
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

*Importação de arquivos EXCEL*

In [15]:
hospital = 'CENTRAL_TATUAPE'
mes = 'MAR'
caminho = ('G:/Drives compartilhados/Qualidade/ACURÁCIA/INDICADORES CC/2026/MAR/')
df = pd.read_excel(caminho + 'CATE3136_' + hospital + '_' + mes + '26.xlsx')
df_bck = df.copy()

In [3]:
df['Cor'] = ''

In [4]:
df['Setor/Sala'].value_counts()
df['Setor/Sala'].str.contains('Hemodinâmica|Centro Obstétrico', case=False, na=False)

0      False
1      False
2      False
3      False
4      False
       ...
331    False
332    False
333    False
334    False
335    False
Name: Setor/Sala, Length: 336, dtype: bool

In [5]:
verde = df['Setor/Sala'].str.contains('Hemodinâmica|Centro Obstétrico', case=False, na=False)
df.loc[verde, 'Cor'] = 'Verde'

print(df[df['Setor/Sala'].str.contains('Hemodinâmica|Centro Obstétrico', case=False, na=False)])

Empty DataFrame
Columns: [Nr atendimento, Dt Internacao, Dt alta, Nm paciente, Dt nascimento, Idade, Sexo, Ds email, Nr telefone, Nr prescricao, Nr cirurgia, Ds tipo cirurgia, Porte, COD. TUSS, Ds procedimento, Proced adicional, Início previsto, Dt cirurgia, Dt termino, Nm cirurgiao, Duração Prevista, Duração Real, Ds especialidade cirurgiao, Nm anestesista, Tipo Anestesia, Asa, Cid doenca, Ds cid, Cid definitivo, Ds cid def, Tipo Posição, Superfície de Suporte, Posição Membros, Pontuação Elpo, Carater Cirurgia, Setor/Sala, Cpf, Crm, Convenio, OPME (Agenda), Cor]
Index: []

*Obtendo nomes das colunas*

In [6]:
df.columns

Index(['Nr atendimento', 'Dt Internacao', 'Dt alta', 'Nm paciente',
       'Dt nascimento', 'Idade', 'Sexo', 'Ds email', 'Nr telefone',
       'Nr prescricao', 'Nr cirurgia', 'Ds tipo cirurgia', 'Porte',
       'COD. TUSS', 'Ds procedimento', 'Proced adicional', 'Início previsto',
       'Dt cirurgia', 'Dt termino', 'Nm cirurgiao', 'Duração Prevista',
       'Duração Real', 'Ds especialidade cirurgiao', 'Nm anestesista',
       'Tipo Anestesia', 'Asa', 'Cid doenca', 'Ds cid', 'Cid definitivo',
       'Ds cid def', 'Tipo Posição', 'Superfície de Suporte',
       'Posição Membros', 'Pontuação Elpo', 'Carater Cirurgia', 'Setor/Sala',
       'Cpf', 'Crm', 'Convenio', 'OPME (Agenda)', 'Cor'],
      dtype='str')

*Remover linhas que não contem resposta*

In [7]:
condicao = (
    df['Setor/Sala'].isnull() &
    df['Tipo Anestesia'].str.contains(
        'Local|Local Assistida|Sem Analgesia',
        case=False,
        na=False
    )
)
df.loc[condicao, 'Cor'] = 'Amarelo'
print(df.loc[condicao, 'Cor'])

Series([], Name: Cor, dtype: str)

*Filtrando os dados*

In [8]:
palavras = (
    'Postectomia',
    'Vasectomia',
    'Retirada de Cateter',
    'Retirada de duplo j',
    'Entensos Ferimentos',
    'Endoscopia',
    'Colonoscopia',
    'Infiltração',
    'Denervação',
    'Bloqueio',
    'Túnel',
    'Exérese',
    'Aspiração Manual'    
)

padrao = '|'.join(palavras)

vazios = (
    df['Tipo Anestesia'].isnull() &
    df['Ds procedimento'].str.contains(padrao, case=False, na=False) &
    df['Proced adicional'].isnull()
)
df.loc[vazios, 'Tipo Anestesia'] = 'Sedação'

In [9]:
# Adicionando "Anestesia" em campos vazios
df.loc[
    df['Tipo Anestesia'].isnull() |
    (df['Tipo Anestesia'].str.strip() == ''),
    'Tipo Anestesia'
] = 'Anestesia'

*Removendo caracteres indesejados*

In [10]:
len(df)

336

In [11]:
display(df_bck.loc[26:26])

display(df.loc[26:26])

,Nr atendimento,Dt Internacao,Dt alta,Nm paciente,Dt nascimento,Idade,Sexo,Ds email,Nr telefone,Nr prescricao,Nr cirurgia,Ds tipo cirurgia,Porte,COD. TUSS,Ds procedimento,Proced adicional,Início previsto,Dt cirurgia,Dt termino,Nm cirurgiao,Duração Prevista,Duração Real,Ds especialidade cirurgiao,Nm anestesista,Tipo Anestesia,Asa,Cid doenca,Ds cid,Cid definitivo,Ds cid def,Tipo Posição,Superfície de Suporte,Posição Membros,Pontuação Elpo,Carater Cirurgia,Setor/Sala,Cpf,Crm,Convenio,OPME (Agenda)
26,1908883,2026-03-23,2026-03-24 00:00:00,Camila Gomes da Silva,1989-12-11,37,Feminino,CAMIlasantos.4653@gmail.com,Fone_I: 11 966936947;,8074937,70387,Limpa,Pequeno,31602126,Bloqueio Facetário Para-Espinhoso,Bloqueio de Nervo Periférico; Bloqueio Facetár...,2026-03-23 16:00:00,2026-03-23,2026-03-23 00:00:00,Oendell Proença Falcão,60,60,Ortopedia e Traumatologia,Marcos Bastos dos Santos,Sedação,I - Saudável,M511,TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...,M511,TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...,,,,,Eletiva,Centro Cirurgico - HCO CC2,23286653810,203720,BRADESCO SEGUR,Sim

,Nr atendimento,Dt Internacao,Dt alta,Nm paciente,Dt nascimento,Idade,Sexo,Ds email,Nr telefone,Nr prescricao,Nr cirurgia,Ds tipo cirurgia,Porte,COD. TUSS,Ds procedimento,Proced adicional,Início previsto,Dt cirurgia,Dt termino,Nm cirurgiao,Duração Prevista,Duração Real,Ds especialidade cirurgiao,Nm anestesista,Tipo Anestesia,Asa,Cid doenca,Ds cid,Cid definitivo,Ds cid def,Tipo Posição,Superfície de Suporte,Posição Membros,Pontuação Elpo,Carater Cirurgia,Setor/Sala,Cpf,Crm,Convenio,OPME (Agenda),Cor
26,1908883,2026-03-23,2026-03-24 00:00:00,Camila Gomes da Silva,1989-12-11,37,Feminino,CAMIlasantos.4653@gmail.com,Fone_I: 11 966936947;,8074937,70387,Limpa,Pequeno,31602126,Bloqueio Facetário Para-Espinhoso,Bloqueio de Nervo Periférico; Bloqueio Facetár...,2026-03-23 16:00:00,2026-03-23,2026-03-23 00:00:00,Oendell Proença Falcão,60,60,Ortopedia e Traumatologia,Marcos Bastos dos Santos,Sedação,I - Saudável,M511,TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...,M511,TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...,,,,,Eletiva,Centro Cirurgico - HCO CC2,23286653810,203720,BRADESCO SEGUR,Sim,

*Concatenando dataframes*

In [12]:
# Concatenando dataframes
df_final = (
    pd.concat([verde, condicao, vazios]))
    # .drop_duplicates(subset=['Ds procedimento', 'þÿNr atendimento'], keep='last'))

In [13]:
len(df)

336

In [14]:
df.to_excel(caminho + 'CC_' + hospital + '_' + mes + '2026.xlsx')